_target_: source.networks.Warper3DGS

verbose: True
viewpoint_stack: !!null
sh_degree: 3

opt:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 1.6e-06
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.025
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 30000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  random_background: false
  save_iterations: [3000, 7000, 15000, 30000]
  batch_size: 64
  exposure_lr_init: 0.01
  exposure_lr_final: 0.0001
  exposure_lr_delay_steps: 0
  exposure_lr_delay_mult: 0.0

  TRAIN_CAM_IDX_TO_LOG: 50
  TEST_CAM_IDX_TO_LOG: 10

pipe:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False
  antialiasing: False 

dataset:
  densify_until_iter: 15000
  source_path:  '' #path to dataset
  model_path:  '' #path to logs
  images: images
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
  depths: ""
  train_test_exp: False